name: Deploy LaTeX PDF to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy PDF to output folder
        run: |
          mkdir -p out/eng out/fr
          cp CV_CHARF_ENG/cv.pdf out/eng/cv.pdf
          cp CV_CHARF_FR/cv.pdf out/fr/cv.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
