name: Build and Deploy LaTeX PDF to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get install -y texlive-full

      - name: Build PDF
        run: |
          latexmk -pdf -output-directory=out CV_CHARF_ENG/cv.tex

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
